package principal;

import java.awt.Color;
import clases.CambiaPanel;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.WindowConstants;

public class NewJFrame extends javax.swing.JFrame {

  int x, y;

  public NewJFrame() {
    setResizable(false);
    setTitle("Matrices");
    setLocationRelativeTo(null);
    initComponents();
    setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

    this.setLocationRelativeTo(this);

    new CambiaPanel(pnlPrincipal, new paneles.pnlHome());
  }

  //Método para cambiar el icono del JFrame, 
  //Antes debemos cambiar la propiedad IconImage en el diseño del JFrame
  @Override
  public Image getIconImage() {
    Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("icons/matrix.png"));
    return retValue;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    jPanel1 = new javax.swing.JPanel();
    pnlMenu = new javax.swing.JPanel();
    btnPersonal_Home = new rsbuttom.RSButtonMetro();
    jPanel4 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    btnPersonal_Multiplicacion = new rsbuttom.RSButtonMetro();
    btnPersonal_Suma = new rsbuttom.RSButtonMetro();
    btnPersonal_GaussJordan = new rsbuttom.RSButtonMetro();
    jPanel5 = new javax.swing.JPanel();
    jLabel3 = new javax.swing.JLabel();
    seis = new rsbuttom.RSButtonMetro();
    btnPersonal_Gaussiana = new rsbuttom.RSButtonMetro();
    btnPersonal_Inversa = new rsbuttom.RSButtonMetro();
    btnPersonal_Ecuacion = new rsbuttom.RSButtonMetro();
    btnPersonal_EJemplos = new rsbuttom.RSButtonMetro();
    jPanel2 = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    pnlCentro = new javax.swing.JPanel();
    jPanel6 = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    pnlPrincipal = new javax.swing.JPanel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setIconImage(getIconImage());

    jPanel1.setBackground(new java.awt.Color(255, 255, 255));
    jPanel1.setLayout(new java.awt.GridBagLayout());

    pnlMenu.setBackground(new java.awt.Color(239, 238, 244));
    pnlMenu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 5, 0, 0, new java.awt.Color(239, 238, 244)));

    btnPersonal_Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home.png"))); // NOI18N
    btnPersonal_Home.setText("Inicio");
    btnPersonal_Home.setColorHover(new java.awt.Color(204, 204, 204));
    btnPersonal_Home.setColorNormal(new java.awt.Color(204, 204, 204));
    btnPersonal_Home.setColorPressed(new java.awt.Color(204, 204, 204));
    btnPersonal_Home.setColorTextHover(new java.awt.Color(128, 128, 131));
    btnPersonal_Home.setColorTextNormal(new java.awt.Color(128, 128, 131));
    btnPersonal_Home.setColorTextPressed(new java.awt.Color(128, 128, 131));
    btnPersonal_Home.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
    btnPersonal_Home.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    btnPersonal_Home.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
    btnPersonal_Home.setIconTextGap(25);
    btnPersonal_Home.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mousePressed(java.awt.event.MouseEvent evt) {
        btnPersonal_HomeMousePressed(evt);
      }
    });
    btnPersonal_Home.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnPersonal_HomeActionPerformed(evt);
      }
    });

    jPanel4.setBackground(new java.awt.Color(239, 238, 244));
    jPanel4.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N

    jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(128, 128, 131));
    jLabel1.setText("Opciones");

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
      jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel4Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel4Layout.setVerticalGroup(
      jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jLabel1)
        .addContainerGap())
    );

    btnPersonal_Multiplicacion.setBackground(new java.awt.Color(239, 238, 244));
    btnPersonal_Multiplicacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/mult.png"))); // NOI18N
    btnPersonal_Multiplicacion.setText(" Multiplicación de matrices");
    btnPersonal_Multiplicacion.setColorHover(new java.awt.Color(204, 204, 204));
    btnPersonal_Multiplicacion.setColorNormal(new java.awt.Color(239, 238, 244));
    btnPersonal_Multiplicacion.setColorPressed(new java.awt.Color(204, 204, 204));
    btnPersonal_Multiplicacion.setColorTextHover(new java.awt.Color(128, 128, 131));
    btnPersonal_Multiplicacion.setColorTextNormal(new java.awt.Color(128, 128, 131));
    btnPersonal_Multiplicacion.setColorTextPressed(new java.awt.Color(128, 128, 131));
    btnPersonal_Multiplicacion.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
    btnPersonal_Multiplicacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    btnPersonal_Multiplicacion.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
    btnPersonal_Multiplicacion.setIconTextGap(19);
    btnPersonal_Multiplicacion.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mousePressed(java.awt.event.MouseEvent evt) {
        btnPersonal_MultiplicacionMousePressed(evt);
      }
    });
    btnPersonal_Multiplicacion.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnPersonal_MultiplicacionActionPerformed(evt);
      }
    });

    btnPersonal_Suma.setBackground(new java.awt.Color(239, 238, 244));
    btnPersonal_Suma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
    btnPersonal_Suma.setText("Suma de matrices");
    btnPersonal_Suma.setColorHover(new java.awt.Color(204, 204, 204));
    btnPersonal_Suma.setColorNormal(new java.awt.Color(239, 238, 244));
    btnPersonal_Suma.setColorPressed(new java.awt.Color(204, 204, 204));
    btnPersonal_Suma.setColorTextHover(new java.awt.Color(128, 128, 131));
    btnPersonal_Suma.setColorTextNormal(new java.awt.Color(128, 128, 131));
    btnPersonal_Suma.setColorTextPressed(new java.awt.Color(128, 128, 131));
    btnPersonal_Suma.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
    btnPersonal_Suma.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    btnPersonal_Suma.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
    btnPersonal_Suma.setIconTextGap(25);
    btnPersonal_Suma.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mousePressed(java.awt.event.MouseEvent evt) {
        btnPersonal_SumaMousePressed(evt);
      }
    });
    btnPersonal_Suma.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnPersonal_SumaActionPerformed(evt);
      }
    });

    btnPersonal_GaussJordan.setBackground(new java.awt.Color(239, 238, 244));
    btnPersonal_GaussJordan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/gauss_jordaj.png"))); // NOI18N
    btnPersonal_GaussJordan.setText(" Eliminación Gauss-Jordan");
    btnPersonal_GaussJordan.setColorHover(new java.awt.Color(204, 204, 204));
    btnPersonal_GaussJordan.setColorNormal(new java.awt.Color(239, 238, 244));
    btnPersonal_GaussJordan.setColorPressed(new java.awt.Color(204, 204, 204));
    btnPersonal_GaussJordan.setColorTextHover(new java.awt.Color(128, 128, 131));
    btnPersonal_GaussJordan.setColorTextNormal(new java.awt.Color(128, 128, 131));
    btnPersonal_GaussJordan.setColorTextPressed(new java.awt.Color(128, 128, 131));
    btnPersonal_GaussJordan.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
    btnPersonal_GaussJordan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    btnPersonal_GaussJordan.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
    btnPersonal_GaussJordan.setIconTextGap(19);
    btnPersonal_GaussJordan.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mousePressed(java.awt.event.MouseEvent evt) {
        btnPersonal_GaussJordanMousePressed(evt);
      }
    });
    btnPersonal_GaussJordan.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnPersonal_GaussJordanActionPerformed(evt);
      }
    });

    jPanel5.setBackground(new java.awt.Color(239, 238, 244));
    jPanel5.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N

    jLabel3.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
    jLabel3.setForeground(new java.awt.Color(128, 128, 131));
    jLabel3.setText("Creador");

    javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
    jPanel5.setLayout(jPanel5Layout);
    jPanel5Layout.setHorizontalGroup(
      jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel5Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel3)
        .addContainerGap(66, Short.MAX_VALUE))
    );
    jPanel5Layout.setVerticalGroup(
      jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jLabel3)
        .addContainerGap())
    );

    seis.setBackground(new java.awt.Color(239, 238, 244));
    seis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/acerca_De.png"))); // NOI18N
    seis.setText("About me");
    seis.setColorHover(new java.awt.Color(204, 204, 204));
    seis.setColorNormal(new java.awt.Color(239, 238, 244));
    seis.setColorPressed(new java.awt.Color(204, 204, 204));
    seis.setColorTextHover(new java.awt.Color(128, 128, 131));
    seis.setColorTextNormal(new java.awt.Color(128, 128, 131));
    seis.setColorTextPressed(new java.awt.Color(128, 128, 131));
    seis.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
    seis.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    seis.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
    seis.setIconTextGap(25);
    seis.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mousePressed(java.awt.event.MouseEvent evt) {
        seisMousePressed(evt);
      }
    });
    seis.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        seisActionPerformed(evt);
      }
    });

    btnPersonal_Gaussiana.setBackground(new java.awt.Color(239, 238, 244));
    btnPersonal_Gaussiana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/gaussiana.png"))); // NOI18N
    btnPersonal_Gaussiana.setText(" Eliminación Gaussiana");
    btnPersonal_Gaussiana.setColorHover(new java.awt.Color(204, 204, 204));
    btnPersonal_Gaussiana.setColorNormal(new java.awt.Color(239, 238, 244));
    btnPersonal_Gaussiana.setColorPressed(new java.awt.Color(204, 204, 204));
    btnPersonal_Gaussiana.setColorTextHover(new java.awt.Color(128, 128, 131));
    btnPersonal_Gaussiana.setColorTextNormal(new java.awt.Color(128, 128, 131));
    btnPersonal_Gaussiana.setColorTextPressed(new java.awt.Color(128, 128, 131));
    btnPersonal_Gaussiana.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
    btnPersonal_Gaussiana.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    btnPersonal_Gaussiana.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
    btnPersonal_Gaussiana.setIconTextGap(19);
    btnPersonal_Gaussiana.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mousePressed(java.awt.event.MouseEvent evt) {
        btnPersonal_GaussianaMousePressed(evt);
      }
    });
    btnPersonal_Gaussiana.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnPersonal_GaussianaActionPerformed(evt);
      }
    });

    btnPersonal_Inversa.setBackground(new java.awt.Color(239, 238, 244));
    btnPersonal_Inversa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/inversa.png"))); // NOI18N
    btnPersonal_Inversa.setText("   Inversa de una matriz");
    btnPersonal_Inversa.setColorHover(new java.awt.Color(204, 204, 204));
    btnPersonal_Inversa.setColorNormal(new java.awt.Color(239, 238, 244));
    btnPersonal_Inversa.setColorPressed(new java.awt.Color(204, 204, 204));
    btnPersonal_Inversa.setColorTextHover(new java.awt.Color(128, 128, 131));
    btnPersonal_Inversa.setColorTextNormal(new java.awt.Color(128, 128, 131));
    btnPersonal_Inversa.setColorTextPressed(new java.awt.Color(128, 128, 131));
    btnPersonal_Inversa.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
    btnPersonal_Inversa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    btnPersonal_Inversa.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
    btnPersonal_Inversa.setIconTextGap(19);
    btnPersonal_Inversa.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mousePressed(java.awt.event.MouseEvent evt) {
        btnPersonal_InversaMousePressed(evt);
      }
    });
    btnPersonal_Inversa.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnPersonal_InversaActionPerformed(evt);
      }
    });

    btnPersonal_Ecuacion.setBackground(new java.awt.Color(239, 238, 244));
    btnPersonal_Ecuacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ecuacion.png"))); // NOI18N
    btnPersonal_Ecuacion.setText("   Resolver Ecuciones con adjunta");
    btnPersonal_Ecuacion.setColorHover(new java.awt.Color(204, 204, 204));
    btnPersonal_Ecuacion.setColorNormal(new java.awt.Color(239, 238, 244));
    btnPersonal_Ecuacion.setColorPressed(new java.awt.Color(204, 204, 204));
    btnPersonal_Ecuacion.setColorTextHover(new java.awt.Color(128, 128, 131));
    btnPersonal_Ecuacion.setColorTextNormal(new java.awt.Color(128, 128, 131));
    btnPersonal_Ecuacion.setColorTextPressed(new java.awt.Color(128, 128, 131));
    btnPersonal_Ecuacion.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
    btnPersonal_Ecuacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    btnPersonal_Ecuacion.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
    btnPersonal_Ecuacion.setIconTextGap(19);
    btnPersonal_Ecuacion.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mousePressed(java.awt.event.MouseEvent evt) {
        btnPersonal_EcuacionMousePressed(evt);
      }
    });
    btnPersonal_Ecuacion.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnPersonal_EcuacionActionPerformed(evt);
      }
    });

    btnPersonal_EJemplos.setBackground(new java.awt.Color(239, 238, 244));
    btnPersonal_EJemplos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ejemplos.png"))); // NOI18N
    btnPersonal_EJemplos.setText("   Ejemplos de matrices");
    btnPersonal_EJemplos.setColorHover(new java.awt.Color(204, 204, 204));
    btnPersonal_EJemplos.setColorNormal(new java.awt.Color(239, 238, 244));
    btnPersonal_EJemplos.setColorPressed(new java.awt.Color(204, 204, 204));
    btnPersonal_EJemplos.setColorTextHover(new java.awt.Color(128, 128, 131));
    btnPersonal_EJemplos.setColorTextNormal(new java.awt.Color(128, 128, 131));
    btnPersonal_EJemplos.setColorTextPressed(new java.awt.Color(128, 128, 131));
    btnPersonal_EJemplos.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
    btnPersonal_EJemplos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    btnPersonal_EJemplos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
    btnPersonal_EJemplos.setIconTextGap(19);
    btnPersonal_EJemplos.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mousePressed(java.awt.event.MouseEvent evt) {
        btnPersonal_EJemplosMousePressed(evt);
      }
    });
    btnPersonal_EJemplos.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnPersonal_EJemplosActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
    pnlMenu.setLayout(pnlMenuLayout);
    pnlMenuLayout.setHorizontalGroup(
      pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(btnPersonal_Inversa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(pnlMenuLayout.createSequentialGroup()
        .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnPersonal_Ecuacion, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
          .addComponent(btnPersonal_EJemplos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(seis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGap(0, 0, Short.MAX_VALUE))
      .addComponent(btnPersonal_Home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(btnPersonal_Suma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(btnPersonal_Multiplicacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(btnPersonal_Gaussiana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(btnPersonal_GaussJordan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    pnlMenuLayout.setVerticalGroup(
      pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlMenuLayout.createSequentialGroup()
        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, 0)
        .addComponent(btnPersonal_Home, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, 0)
        .addComponent(btnPersonal_Suma, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, 0)
        .addComponent(btnPersonal_Multiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, 0)
        .addComponent(btnPersonal_Gaussiana, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, 0)
        .addComponent(btnPersonal_GaussJordan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, 0)
        .addComponent(btnPersonal_Inversa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, 0)
        .addComponent(btnPersonal_Ecuacion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, 0)
        .addComponent(btnPersonal_EJemplos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, 0)
        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, 0)
        .addComponent(seis, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weighty = 8.3;
    gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 1);
    jPanel1.add(pnlMenu, gridBagConstraints);

    jPanel2.setBackground(new java.awt.Color(38, 86, 186));
    jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
      public void mouseDragged(java.awt.event.MouseEvent evt) {
        jPanel2MouseDragged(evt);
      }
    });
    jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mousePressed(java.awt.event.MouseEvent evt) {
        jPanel2MousePressed(evt);
      }
    });

    jLabel2.setBackground(new java.awt.Color(255, 255, 255));
    jLabel2.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(255, 255, 255));
    jLabel2.setText("Guía - Algebra lineal");

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addGap(70, 70, 70)
        .addComponent(jLabel2)
        .addContainerGap(850, Short.MAX_VALUE))
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.gridwidth = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
    gridBagConstraints.weightx = 0.2;
    jPanel1.add(jPanel2, gridBagConstraints);

    pnlCentro.setBackground(new java.awt.Color(255, 255, 255));

    jPanel6.setBackground(new java.awt.Color(255, 255, 255));

    javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
    jPanel6.setLayout(jPanel6Layout);
    jPanel6Layout.setHorizontalGroup(
      jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 777, Short.MAX_VALUE)
    );
    jPanel6Layout.setVerticalGroup(
      jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 46, Short.MAX_VALUE)
    );

    jScrollPane1.setBorder(null);

    pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
    pnlPrincipal.setLayout(new javax.swing.BoxLayout(pnlPrincipal, javax.swing.BoxLayout.LINE_AXIS));
    jScrollPane1.setViewportView(pnlPrincipal);

    javax.swing.GroupLayout pnlCentroLayout = new javax.swing.GroupLayout(pnlCentro);
    pnlCentro.setLayout(pnlCentroLayout);
    pnlCentroLayout.setHorizontalGroup(
      pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(pnlCentroLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane1)
        .addContainerGap())
    );
    pnlCentroLayout.setVerticalGroup(
      pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlCentroLayout.createSequentialGroup()
        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.4;
    gridBagConstraints.weighty = 0.1;
    jPanel1.add(pnlCentro, gridBagConstraints);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void btnPersonal_HomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPersonal_HomeMousePressed
      this.btnPersonal_Home.setSelected(true);
      this.btnPersonal_Suma.setSelected(false);
      this.btnPersonal_Multiplicacion.setSelected(false);
      this.btnPersonal_Gaussiana.setSelected(false);
      this.btnPersonal_GaussJordan.setSelected(false);
      this.btnPersonal_Inversa.setSelected(false);
      this.btnPersonal_Ecuacion.setSelected(false);
      this.btnPersonal_EJemplos.setSelected(false);
      this.seis.setSelected(false);
    }//GEN-LAST:event_btnPersonal_HomeMousePressed

    private void btnPersonal_HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonal_HomeActionPerformed
      new CambiaPanel(pnlPrincipal, new paneles.pnlHome());
      if (this.btnPersonal_Home.isSelected()) {
        this.btnPersonal_Home.setColorNormal(new Color(204, 204, 204));
        this.btnPersonal_Home.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_Home.setColorPressed(new Color(204, 204, 204));

        this.btnPersonal_Suma.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_Suma.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_Suma.setColorPressed(new Color(204, 204, 204));

        this.btnPersonal_Multiplicacion.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_Multiplicacion.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_Multiplicacion.setColorPressed(new Color(204, 204, 204));

        this.btnPersonal_Gaussiana.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_Gaussiana.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_Gaussiana.setColorPressed(new Color(204, 204, 204));

        this.btnPersonal_GaussJordan.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_GaussJordan.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_GaussJordan.setColorPressed(new Color(204, 204, 204));

        this.btnPersonal_Inversa.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_Inversa.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_Inversa.setColorPressed(new Color(204, 204, 204));

        this.btnPersonal_Ecuacion.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_Ecuacion.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_Ecuacion.setColorPressed(new Color(204, 204, 204));

        this.btnPersonal_EJemplos.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_EJemplos.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_EJemplos.setColorPressed(new Color(204, 204, 204));

        this.seis.setColorNormal(new Color(239, 238, 244));
        this.seis.setColorHover(new Color(204, 204, 204));
        this.seis.setColorPressed(new Color(204, 204, 204));
      } else {
        this.btnPersonal_Home.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_Home.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_Home.setColorPressed(new Color(204, 204, 204));
      }
    }//GEN-LAST:event_btnPersonal_HomeActionPerformed

    private void btnPersonal_MultiplicacionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPersonal_MultiplicacionMousePressed
      this.btnPersonal_Home.setSelected(false);
      this.btnPersonal_Suma.setSelected(false);
      this.btnPersonal_Multiplicacion.setSelected(true);
      this.btnPersonal_Gaussiana.setSelected(false);
      this.btnPersonal_GaussJordan.setSelected(false);
      this.btnPersonal_Inversa.setSelected(false);
      this.btnPersonal_Ecuacion.setSelected(false);
      this.btnPersonal_EJemplos.setSelected(false);
      this.seis.setSelected(false);
    }//GEN-LAST:event_btnPersonal_MultiplicacionMousePressed

    private void btnPersonal_MultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonal_MultiplicacionActionPerformed
      new CambiaPanel(pnlPrincipal, new paneles.pnl_Multiplicacion_Matrices());
      if (this.btnPersonal_Multiplicacion.isSelected()) {
        this.btnPersonal_Multiplicacion.setColorNormal(new Color(204, 204, 204));
        this.btnPersonal_Multiplicacion.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_Multiplicacion.setColorPressed(new Color(204, 204, 204));

        this.btnPersonal_Home.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_Home.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_Home.setColorPressed(new Color(204, 204, 204));

        this.btnPersonal_Suma.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_Suma.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_Suma.setColorPressed(new Color(204, 204, 204));

        this.btnPersonal_Gaussiana.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_Gaussiana.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_Gaussiana.setColorPressed(new Color(204, 204, 204));

        this.btnPersonal_GaussJordan.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_GaussJordan.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_GaussJordan.setColorPressed(new Color(204, 204, 204));

        this.btnPersonal_Inversa.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_Inversa.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_Inversa.setColorPressed(new Color(204, 204, 204));

        this.btnPersonal_Ecuacion.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_Ecuacion.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_Ecuacion.setColorPressed(new Color(204, 204, 204));

        this.btnPersonal_EJemplos.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_EJemplos.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_EJemplos.setColorPressed(new Color(204, 204, 204));

        this.seis.setColorNormal(new Color(239, 238, 244));
        this.seis.setColorHover(new Color(204, 204, 204));
        this.seis.setColorPressed(new Color(204, 204, 204));

      } else {
        this.btnPersonal_Multiplicacion.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_Multiplicacion.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_Multiplicacion.setColorPressed(new Color(204, 204, 204));
      }
    }//GEN-LAST:event_btnPersonal_MultiplicacionActionPerformed

    private void btnPersonal_SumaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPersonal_SumaMousePressed
      this.btnPersonal_Home.setSelected(false);
      this.btnPersonal_Suma.setSelected(true);
      this.btnPersonal_Multiplicacion.setSelected(false);
      this.btnPersonal_Gaussiana.setSelected(false);
      this.btnPersonal_GaussJordan.setSelected(false);
      this.btnPersonal_Inversa.setSelected(false);
      this.btnPersonal_Ecuacion.setSelected(false);
      this.btnPersonal_EJemplos.setSelected(false);
      this.seis.setSelected(false);
    }//GEN-LAST:event_btnPersonal_SumaMousePressed

    private void btnPersonal_SumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonal_SumaActionPerformed
      new CambiaPanel(pnlPrincipal, new paneles.Suma_Matrices());
      if (this.btnPersonal_Suma.isSelected()) {
        this.btnPersonal_Suma.setColorNormal(new Color(204, 204, 204));
        this.btnPersonal_Suma.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_Suma.setColorPressed(new Color(204, 204, 204));

        this.btnPersonal_Home.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_Home.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_Home.setColorPressed(new Color(204, 204, 204));

        this.btnPersonal_Multiplicacion.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_Multiplicacion.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_Multiplicacion.setColorPressed(new Color(204, 204, 204));

        this.btnPersonal_Gaussiana.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_Gaussiana.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_Gaussiana.setColorPressed(new Color(204, 204, 204));

        this.btnPersonal_GaussJordan.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_GaussJordan.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_GaussJordan.setColorPressed(new Color(204, 204, 204));

        this.btnPersonal_Inversa.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_Inversa.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_Inversa.setColorPressed(new Color(204, 204, 204));

        this.btnPersonal_Ecuacion.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_Ecuacion.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_Ecuacion.setColorPressed(new Color(204, 204, 204));

        this.btnPersonal_EJemplos.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_EJemplos.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_EJemplos.setColorPressed(new Color(204, 204, 204));

        this.seis.setColorNormal(new Color(239, 238, 244));
        this.seis.setColorHover(new Color(204, 204, 204));
        this.seis.setColorPressed(new Color(204, 204, 204));

      } else {
        this.btnPersonal_Suma.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_Suma.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_Suma.setColorPressed(new Color(204, 204, 204));
      }
    }//GEN-LAST:event_btnPersonal_SumaActionPerformed

    private void btnPersonal_GaussJordanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPersonal_GaussJordanMousePressed
      this.btnPersonal_Home.setSelected(false);
      this.btnPersonal_Suma.setSelected(false);
      this.btnPersonal_Multiplicacion.setSelected(false);
      this.btnPersonal_Gaussiana.setSelected(false);
      this.btnPersonal_GaussJordan.setSelected(true);
      this.btnPersonal_Inversa.setSelected(false);
      this.btnPersonal_Ecuacion.setSelected(false);
      this.btnPersonal_EJemplos.setSelected(false);
      this.seis.setSelected(false);
    }//GEN-LAST:event_btnPersonal_GaussJordanMousePressed

    private void btnPersonal_GaussJordanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonal_GaussJordanActionPerformed
      new CambiaPanel(pnlPrincipal, new paneles.pnl_GaussJordan());
      if (this.btnPersonal_GaussJordan.isSelected()) {
        this.btnPersonal_Home.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_Home.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_Home.setColorPressed(new Color(204, 204, 204));

        this.btnPersonal_Suma.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_Suma.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_Suma.setColorPressed(new Color(204, 204, 204));

        this.btnPersonal_Multiplicacion.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_Multiplicacion.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_Multiplicacion.setColorPressed(new Color(204, 204, 204));

        this.btnPersonal_Gaussiana.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_Gaussiana.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_Gaussiana.setColorPressed(new Color(204, 204, 204));

        this.btnPersonal_GaussJordan.setColorNormal(new Color(204, 204, 204));
        this.btnPersonal_GaussJordan.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_GaussJordan.setColorPressed(new Color(204, 204, 204));

        this.btnPersonal_Inversa.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_Inversa.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_Inversa.setColorPressed(new Color(204, 204, 204));

        this.btnPersonal_Ecuacion.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_Ecuacion.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_Ecuacion.setColorPressed(new Color(204, 204, 204));

        this.btnPersonal_EJemplos.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_EJemplos.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_EJemplos.setColorPressed(new Color(204, 204, 204));

        this.seis.setColorNormal(new Color(239, 238, 244));
        this.seis.setColorHover(new Color(204, 204, 204));
        this.seis.setColorPressed(new Color(204, 204, 204));

      } else {
        this.btnPersonal_GaussJordan.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_GaussJordan.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_GaussJordan.setColorPressed(new Color(204, 204, 204));
      }
    }//GEN-LAST:event_btnPersonal_GaussJordanActionPerformed

    private void seisMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seisMousePressed
      this.btnPersonal_Home.setSelected(false);
      this.btnPersonal_Suma.setSelected(false);
      this.btnPersonal_Multiplicacion.setSelected(false);
      this.btnPersonal_Gaussiana.setSelected(false);
      this.btnPersonal_GaussJordan.setSelected(false);
      this.btnPersonal_Inversa.setSelected(false);
      this.btnPersonal_Ecuacion.setSelected(false);
      this.btnPersonal_EJemplos.setSelected(false);
      this.seis.setSelected(true);
    }//GEN-LAST:event_seisMousePressed

    private void seisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seisActionPerformed
      new CambiaPanel(pnlPrincipal, new paneles.pnl_AboutMe());
      if (this.seis.isSelected()) {
        this.btnPersonal_Home.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_Home.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_Home.setColorPressed(new Color(204, 204, 204));

        this.btnPersonal_Suma.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_Suma.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_Suma.setColorPressed(new Color(204, 204, 204));

        this.btnPersonal_Multiplicacion.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_Multiplicacion.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_Multiplicacion.setColorPressed(new Color(204, 204, 204));

        this.btnPersonal_Gaussiana.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_Gaussiana.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_Gaussiana.setColorPressed(new Color(204, 204, 204));

        this.btnPersonal_GaussJordan.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_GaussJordan.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_GaussJordan.setColorPressed(new Color(204, 204, 204));

        this.btnPersonal_Inversa.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_Inversa.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_Inversa.setColorPressed(new Color(204, 204, 204));

        this.btnPersonal_Ecuacion.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_Ecuacion.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_Ecuacion.setColorPressed(new Color(204, 204, 204));

        this.btnPersonal_EJemplos.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_EJemplos.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_EJemplos.setColorPressed(new Color(204, 204, 204));

        this.seis.setColorNormal(new Color(204, 204, 204));
        this.seis.setColorHover(new Color(204, 204, 204));
        this.seis.setColorPressed(new Color(204, 204, 204));

      } else {
        this.seis.setColorNormal(new Color(239, 238, 244));
        this.seis.setColorHover(new Color(204, 204, 204));
        this.seis.setColorPressed(new Color(204, 204, 204));
      }
    }//GEN-LAST:event_seisActionPerformed

    private void btnPersonal_GaussianaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPersonal_GaussianaMousePressed
      this.btnPersonal_Home.setSelected(false);
      this.btnPersonal_Suma.setSelected(false);
      this.btnPersonal_Multiplicacion.setSelected(false);
      this.btnPersonal_Gaussiana.setSelected(true);
      this.btnPersonal_GaussJordan.setSelected(false);
      this.btnPersonal_Inversa.setSelected(false);
      this.btnPersonal_Ecuacion.setSelected(false);
      this.btnPersonal_EJemplos.setSelected(false);
      this.seis.setSelected(false);
    }//GEN-LAST:event_btnPersonal_GaussianaMousePressed

    private void btnPersonal_GaussianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonal_GaussianaActionPerformed
      new CambiaPanel(pnlPrincipal, new paneles.pnl_Gaussiana());
      if (this.btnPersonal_Gaussiana.isSelected()) {
        this.btnPersonal_Home.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_Home.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_Home.setColorPressed(new Color(204, 204, 204));

        this.btnPersonal_Suma.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_Suma.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_Suma.setColorPressed(new Color(204, 204, 204));

        this.btnPersonal_Multiplicacion.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_Multiplicacion.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_Multiplicacion.setColorPressed(new Color(204, 204, 204));

        this.btnPersonal_Gaussiana.setColorNormal(new Color(204, 204, 204));
        this.btnPersonal_Gaussiana.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_Gaussiana.setColorPressed(new Color(204, 204, 204));

        this.btnPersonal_GaussJordan.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_GaussJordan.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_GaussJordan.setColorPressed(new Color(204, 204, 204));

        this.btnPersonal_Inversa.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_Inversa.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_Inversa.setColorPressed(new Color(204, 204, 204));

        this.btnPersonal_Ecuacion.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_Ecuacion.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_Ecuacion.setColorPressed(new Color(204, 204, 204));

        this.btnPersonal_EJemplos.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_EJemplos.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_EJemplos.setColorPressed(new Color(204, 204, 204));

        this.seis.setColorNormal(new Color(239, 238, 244));
        this.seis.setColorHover(new Color(204, 204, 204));
        this.seis.setColorPressed(new Color(204, 204, 204));

      } else {
        this.btnPersonal_Gaussiana.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_Gaussiana.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_Gaussiana.setColorPressed(new Color(204, 204, 204));
      }
    }//GEN-LAST:event_btnPersonal_GaussianaActionPerformed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
      //Point mueve = MouseInfo.getPointerInfo().getLocation();
      //this.setLocation(mueve.x - x, mueve.y - y);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
      //x = evt.getX();
      //y = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void btnPersonal_InversaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPersonal_InversaMousePressed
      // TODO add your handling code here:
      this.btnPersonal_Home.setSelected(false);
      this.btnPersonal_Suma.setSelected(false);
      this.btnPersonal_Multiplicacion.setSelected(false);
      this.btnPersonal_Gaussiana.setSelected(false);
      this.btnPersonal_GaussJordan.setSelected(false);
      this.btnPersonal_Inversa.setSelected(true);
      this.btnPersonal_Ecuacion.setSelected(false);
      this.btnPersonal_EJemplos.setSelected(false);
      this.seis.setSelected(false);
    }//GEN-LAST:event_btnPersonal_InversaMousePressed

    private void btnPersonal_InversaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonal_InversaActionPerformed
      // TODO add your handling code here:
      new CambiaPanel(pnlPrincipal, new paneles.pnl_Inversa());
      if (this.btnPersonal_Inversa.isSelected()) {
        this.btnPersonal_Home.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_Home.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_Home.setColorPressed(new Color(204, 204, 204));

        this.btnPersonal_Suma.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_Suma.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_Suma.setColorPressed(new Color(204, 204, 204));

        this.btnPersonal_Multiplicacion.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_Multiplicacion.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_Multiplicacion.setColorPressed(new Color(204, 204, 204));

        this.btnPersonal_Gaussiana.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_Gaussiana.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_Gaussiana.setColorPressed(new Color(204, 204, 204));

        this.btnPersonal_GaussJordan.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_GaussJordan.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_GaussJordan.setColorPressed(new Color(204, 204, 204));

        this.btnPersonal_Inversa.setColorNormal(new Color(204, 204, 204));
        this.btnPersonal_Inversa.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_Inversa.setColorPressed(new Color(204, 204, 204));

        this.btnPersonal_Ecuacion.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_Ecuacion.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_Ecuacion.setColorPressed(new Color(204, 204, 204));

        this.btnPersonal_EJemplos.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_EJemplos.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_EJemplos.setColorPressed(new Color(204, 204, 204));

        this.seis.setColorNormal(new Color(239, 238, 244));
        this.seis.setColorHover(new Color(204, 204, 204));
        this.seis.setColorPressed(new Color(204, 204, 204));

      } else {
        this.btnPersonal_Inversa.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_Inversa.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_Inversa.setColorPressed(new Color(204, 204, 204));
      }
    }//GEN-LAST:event_btnPersonal_InversaActionPerformed

    private void btnPersonal_EcuacionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPersonal_EcuacionMousePressed
      // TODO add your handling code here:
      this.btnPersonal_Home.setSelected(false);
      this.btnPersonal_Suma.setSelected(false);
      this.btnPersonal_Multiplicacion.setSelected(false);
      this.btnPersonal_Gaussiana.setSelected(false);
      this.btnPersonal_GaussJordan.setSelected(false);
      this.btnPersonal_Inversa.setSelected(false);
      this.btnPersonal_Ecuacion.setSelected(true);
      this.btnPersonal_EJemplos.setSelected(false);
      this.seis.setSelected(false);
    }//GEN-LAST:event_btnPersonal_EcuacionMousePressed

    private void btnPersonal_EcuacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonal_EcuacionActionPerformed
      // TODO add your handling code here:
      new CambiaPanel(pnlPrincipal, new paneles.pnl_Ecuacion());
      if (this.btnPersonal_Ecuacion.isSelected()) {
        this.btnPersonal_Home.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_Home.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_Home.setColorPressed(new Color(204, 204, 204));

        this.btnPersonal_Suma.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_Suma.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_Suma.setColorPressed(new Color(204, 204, 204));

        this.btnPersonal_Multiplicacion.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_Multiplicacion.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_Multiplicacion.setColorPressed(new Color(204, 204, 204));

        this.btnPersonal_Gaussiana.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_Gaussiana.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_Gaussiana.setColorPressed(new Color(204, 204, 204));

        this.btnPersonal_GaussJordan.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_GaussJordan.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_GaussJordan.setColorPressed(new Color(204, 204, 204));

        this.btnPersonal_Inversa.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_Inversa.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_Inversa.setColorPressed(new Color(204, 204, 204));

        this.btnPersonal_Ecuacion.setColorNormal(new Color(204, 204, 204));
        this.btnPersonal_Ecuacion.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_Ecuacion.setColorPressed(new Color(204, 204, 204));

        this.btnPersonal_EJemplos.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_EJemplos.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_EJemplos.setColorPressed(new Color(204, 204, 204));

        this.seis.setColorNormal(new Color(239, 238, 244));
        this.seis.setColorHover(new Color(204, 204, 204));
        this.seis.setColorPressed(new Color(204, 204, 204));

      } else {
        this.btnPersonal_Ecuacion.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_Ecuacion.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_Ecuacion.setColorPressed(new Color(204, 204, 204));
      }
    }//GEN-LAST:event_btnPersonal_EcuacionActionPerformed

    private void btnPersonal_EJemplosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPersonal_EJemplosMousePressed
      // TODO add your handling code here:
      this.btnPersonal_Home.setSelected(false);
      this.btnPersonal_Suma.setSelected(false);
      this.btnPersonal_Multiplicacion.setSelected(false);
      this.btnPersonal_Gaussiana.setSelected(false);
      this.btnPersonal_GaussJordan.setSelected(false);
      this.btnPersonal_Inversa.setSelected(false);
      this.btnPersonal_Ecuacion.setSelected(false);
      this.btnPersonal_EJemplos.setSelected(true);
    }//GEN-LAST:event_btnPersonal_EJemplosMousePressed

    private void btnPersonal_EJemplosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonal_EJemplosActionPerformed
      // TODO add your handling code here:
      new CambiaPanel(pnlPrincipal, new paneles.pnl_Ejemplos());
      if (this.btnPersonal_EJemplos.isSelected()) {
        this.btnPersonal_Home.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_Home.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_Home.setColorPressed(new Color(204, 204, 204));

        this.btnPersonal_Suma.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_Suma.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_Suma.setColorPressed(new Color(204, 204, 204));

        this.btnPersonal_Multiplicacion.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_Multiplicacion.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_Multiplicacion.setColorPressed(new Color(204, 204, 204));

        this.btnPersonal_Gaussiana.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_Gaussiana.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_Gaussiana.setColorPressed(new Color(204, 204, 204));

        this.btnPersonal_GaussJordan.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_GaussJordan.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_GaussJordan.setColorPressed(new Color(204, 204, 204));

        this.btnPersonal_Inversa.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_Inversa.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_Inversa.setColorPressed(new Color(204, 204, 204));

        this.btnPersonal_Ecuacion.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_Ecuacion.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_Ecuacion.setColorPressed(new Color(204, 204, 204));

        this.btnPersonal_EJemplos.setColorNormal(new Color(204, 204, 204));
        this.btnPersonal_EJemplos.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_EJemplos.setColorPressed(new Color(204, 204, 204));

        this.seis.setColorNormal(new Color(239, 238, 244));
        this.seis.setColorHover(new Color(204, 204, 204));
        this.seis.setColorPressed(new Color(204, 204, 204));

      } else {
        this.btnPersonal_EJemplos.setColorNormal(new Color(239, 238, 244));
        this.btnPersonal_EJemplos.setColorHover(new Color(204, 204, 204));
        this.btnPersonal_EJemplos.setColorPressed(new Color(204, 204, 204));
      }
    }//GEN-LAST:event_btnPersonal_EJemplosActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new NewJFrame().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private rsbuttom.RSButtonMetro btnPersonal_EJemplos;
  private rsbuttom.RSButtonMetro btnPersonal_Ecuacion;
  private rsbuttom.RSButtonMetro btnPersonal_GaussJordan;
  private rsbuttom.RSButtonMetro btnPersonal_Gaussiana;
  private rsbuttom.RSButtonMetro btnPersonal_Home;
  private rsbuttom.RSButtonMetro btnPersonal_Inversa;
  private rsbuttom.RSButtonMetro btnPersonal_Multiplicacion;
  private rsbuttom.RSButtonMetro btnPersonal_Suma;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JPanel jPanel5;
  private javax.swing.JPanel jPanel6;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JPanel pnlCentro;
  private javax.swing.JPanel pnlMenu;
  private javax.swing.JPanel pnlPrincipal;
  private rsbuttom.RSButtonMetro seis;
  // End of variables declaration//GEN-END:variables
}
