package paneles;

import clases.Tabla_Iteraciones;
import java.awt.Color;

public class pnl_Ejemplos extends javax.swing.JPanel {
    
    Tabla_Iteraciones iteraciones = new Tabla_Iteraciones();

    public pnl_Ejemplos() {
        initComponents();
        tbl_Antisimetrica.setEnabled(false);
        tbl_Identidad.setEnabled(false);
        tbl_Nula.setEnabled(false);
        tbl_Simetrica.setEnabled(false);
        tbl_Triangular_Inferior.setEnabled(false);
        tbl_Triangular_Superior.setEnabled(false);
        
        
        jScrollPane1.getViewport().setBackground(Color.white);
        jScrollPane2.getViewport().setBackground(Color.white);
        jScrollPane3.getViewport().setBackground(Color.white);
        jScrollPane4.getViewport().setBackground(Color.white);
        jScrollPane5.getViewport().setBackground(Color.white);
        jScrollPane6.getViewport().setBackground(Color.white);
        
        iteraciones.centrar(tbl_Antisimetrica);
        iteraciones.centrar(tbl_Identidad);
        iteraciones.centrar(tbl_Nula);
        iteraciones.centrar(tbl_Simetrica);
        iteraciones.centrar(tbl_Triangular_Inferior);
        iteraciones.centrar(tbl_Triangular_Superior);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Nula = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_Identidad = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_Triangular_Superior = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbl_Triangular_Inferior = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_Simetrica = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbl_Antisimetrica = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(38, 86, 186));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Ejemplos de matrices");

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        tbl_Nula.setAutoCreateRowSorter(true);
        tbl_Nula.setBackground(new java.awt.Color(204, 199, 228));
        tbl_Nula.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        tbl_Nula.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"0", "0", "0"},
                {"0", "0", "0"},
                {"0", "0", "0"}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        tbl_Nula.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tbl_Nula.setGridColor(new java.awt.Color(155, 154, 163));
        tbl_Nula.setSelectionBackground(new java.awt.Color(204, 199, 228));
        tbl_Nula.setShowGrid(true);
        jScrollPane1.setViewportView(tbl_Nula);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setViewportView(  tbl_Nula  );
        jScrollPane1.setColumnHeaderView( tbl_Nula.getTableHeader());

        jScrollPane1.getColumnHeader().setVisible(false);
        jScrollPane1.revalidate();
        jScrollPane1.setBorder(null);

        jLabel6.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel6.setText("Matriz nula:");

        tbl_Identidad.setAutoCreateRowSorter(true);
        tbl_Identidad.setBackground(new java.awt.Color(204, 199, 228));
        tbl_Identidad.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        tbl_Identidad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "0", "0"},
                {"0", "1", "0"},
                {"0", "0", "1"}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        tbl_Identidad.setGridColor(new java.awt.Color(155, 154, 163));
        tbl_Identidad.setSelectionBackground(new java.awt.Color(204, 199, 228));
        tbl_Identidad.setShowGrid(true);
        tbl_Identidad.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tbl_Identidad);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setViewportView(  tbl_Identidad  );
        jScrollPane3.setColumnHeaderView( tbl_Identidad.getTableHeader());

        jScrollPane3.getColumnHeader().setVisible(false);
        jScrollPane3.revalidate();
        jScrollPane3.setBorder(null);

        jLabel7.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel7.setText("Matriz identidad:");

        jLabel8.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel8.setText("Matriz triangular superior:");

        tbl_Triangular_Superior.setAutoCreateRowSorter(true);
        tbl_Triangular_Superior.setBackground(new java.awt.Color(204, 199, 228));
        tbl_Triangular_Superior.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        tbl_Triangular_Superior.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"2", "5", "9"},
                {"0", "-3", "6"},
                {"0", "0", "1"}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        tbl_Triangular_Superior.setGridColor(new java.awt.Color(155, 154, 163));
        tbl_Triangular_Superior.setSelectionBackground(new java.awt.Color(204, 199, 228));
        tbl_Triangular_Superior.setShowGrid(true);
        tbl_Triangular_Superior.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(tbl_Triangular_Superior);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setViewportView(  tbl_Triangular_Superior  );
        jScrollPane4.setColumnHeaderView( tbl_Triangular_Superior.getTableHeader());

        jScrollPane4.getColumnHeader().setVisible(false);
        jScrollPane4.revalidate();
        jScrollPane4.setBorder(null);

        tbl_Triangular_Inferior.setAutoCreateRowSorter(true);
        tbl_Triangular_Inferior.setBackground(new java.awt.Color(204, 199, 228));
        tbl_Triangular_Inferior.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        tbl_Triangular_Inferior.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"4", "0", "0"},
                {"-1", "2", "0"},
                {"5", "-8", "1"}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        tbl_Triangular_Inferior.setGridColor(new java.awt.Color(155, 154, 163));
        tbl_Triangular_Inferior.setSelectionBackground(new java.awt.Color(204, 199, 228));
        tbl_Triangular_Inferior.setShowGrid(true);
        tbl_Triangular_Inferior.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(tbl_Triangular_Inferior);
        //jScrollPane5.setVerticalScrollBarTPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_NEVER);
        //jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane5.setViewportView(  tbl_Triangular_Inferior  );
        jScrollPane5.setColumnHeaderView( tbl_Triangular_Inferior.getTableHeader());

        jScrollPane5.getColumnHeader().setVisible(false);
        jScrollPane5.revalidate();
        jScrollPane5.setBorder(null);

        jLabel9.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel9.setText("Matriz triangular inferior:");

        jLabel10.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel10.setText("Matriz simetrica:");

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(null);

        tbl_Simetrica.setAutoCreateRowSorter(true);
        tbl_Simetrica.setBackground(new java.awt.Color(204, 199, 228));
        tbl_Simetrica.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        tbl_Simetrica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"3", "1", "2"},
                {"1", "6", "0"},
                {"2", "0", "0"}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        tbl_Simetrica.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tbl_Simetrica.setGridColor(new java.awt.Color(155, 154, 163));
        tbl_Simetrica.setSelectionBackground(new java.awt.Color(204, 199, 228));
        tbl_Simetrica.setShowGrid(true);
        jScrollPane2.setViewportView(tbl_Simetrica);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setViewportView(  tbl_Simetrica  );
        jScrollPane2.setColumnHeaderView( tbl_Simetrica.getTableHeader());

        jScrollPane2.getColumnHeader().setVisible(false);
        jScrollPane2.revalidate();
        jScrollPane2.setBorder(null);

        jScrollPane6.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane6.setBorder(null);

        tbl_Antisimetrica.setAutoCreateRowSorter(true);
        tbl_Antisimetrica.setBackground(new java.awt.Color(204, 199, 228));
        tbl_Antisimetrica.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        tbl_Antisimetrica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"0", "4", "7"},
                {"-4", "0", "-3"},
                {"-7", "3", "0"}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        tbl_Antisimetrica.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tbl_Antisimetrica.setGridColor(new java.awt.Color(155, 154, 163));
        tbl_Antisimetrica.setSelectionBackground(new java.awt.Color(204, 199, 228));
        tbl_Antisimetrica.setShowGrid(true);
        jScrollPane6.setViewportView(tbl_Antisimetrica);
        jScrollPane6.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane6.setViewportView(  tbl_Antisimetrica  );
        jScrollPane6.setColumnHeaderView( tbl_Antisimetrica.getTableHeader());

        jScrollPane6.getColumnHeader().setVisible(false);
        jScrollPane6.revalidate();
        jScrollPane6.setBorder(null);

        jLabel11.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel11.setText("Matriz antisimetrica:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(142, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable tbl_Antisimetrica;
    private javax.swing.JTable tbl_Identidad;
    private javax.swing.JTable tbl_Nula;
    private javax.swing.JTable tbl_Simetrica;
    private javax.swing.JTable tbl_Triangular_Inferior;
    private javax.swing.JTable tbl_Triangular_Superior;
    // End of variables declaration//GEN-END:variables
}
