/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import clases.Convert_To_Fraction;
import javax.swing.JOptionPane;
import clases.Tabla_Iteraciones;
import clases.Inversa_Proceso;
import java.awt.Color;

public class pnl_Inversa extends javax.swing.JPanel {

    /**
     * Creates new form pnlHome
     */
    public pnl_Inversa() {
        initComponents();
        jScrollPane1.getViewport().setBackground(Color.white);
        jScrollPane3.getViewport().setBackground(Color.white);

        tbl_Matriz.setSelectionForeground(Color.black);
        tbl_Resultado1.setSelectionForeground(Color.black);
        tbl_Resultado1.setEnabled(false);

        jLabel7.setVisible(false);
    }
    Tabla_Iteraciones iteraciones = new Tabla_Iteraciones();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        btn_Resolver = new javax.swing.JButton();
        btn_Aceptar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_Resultado1 = new javax.swing.JTable();
        txt_Col = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_filas = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Matriz = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(38, 86, 186));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Inversa de una matriz");

        btn_Resolver.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        btn_Resolver.setText("Calcular inversa");
        btn_Resolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ResolverActionPerformed(evt);
            }
        });

        btn_Aceptar.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        btn_Aceptar.setText("Crear matriz");
        btn_Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AceptarActionPerformed(evt);
            }
        });

        tbl_Resultado1.setBackground(new java.awt.Color(204, 199, 228));
        tbl_Resultado1.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        tbl_Resultado1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbl_Resultado1.setGridColor(new java.awt.Color(155, 154, 163));
        tbl_Resultado1.setSelectionBackground(new java.awt.Color(204, 199, 228));
        tbl_Resultado1.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tbl_Resultado1);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setViewportView(  tbl_Resultado1  );
        jScrollPane3.setColumnHeaderView( tbl_Resultado1.getTableHeader());

        jScrollPane3.getColumnHeader().setVisible(false);
        jScrollPane3.revalidate();
        jScrollPane3.setBorder(null);

        txt_Col.setBackground(new java.awt.Color(239, 238, 244));
        txt_Col.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        txt_Col.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Col.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel6.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel6.setText("Filas de la matriz:");

        txt_filas.setBackground(new java.awt.Color(239, 238, 244));
        txt_filas.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        txt_filas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_filas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txt_filas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_filasActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel2.setText("Columnas de la matriz:");

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        tbl_Matriz.setAutoCreateRowSorter(true);
        tbl_Matriz.setBackground(new java.awt.Color(204, 199, 228));
        tbl_Matriz.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        tbl_Matriz.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbl_Matriz.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tbl_Matriz.setGridColor(new java.awt.Color(155, 154, 163));
        tbl_Matriz.setSelectionBackground(new java.awt.Color(204, 199, 228));
        tbl_Matriz.setShowGrid(true);
        jScrollPane1.setViewportView(tbl_Matriz);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setViewportView(  tbl_Matriz  );
        jScrollPane1.setColumnHeaderView( tbl_Matriz.getTableHeader());

        jScrollPane1.getColumnHeader().setVisible(false);
        jScrollPane1.revalidate();
        jScrollPane1.setBorder(null);

        jLabel7.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel7.setText("Matriz inversa:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_filas, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Col, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_Resolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_Aceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(219, 219, 219)
                                .addComponent(jLabel7))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_filas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Aceptar))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Col, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btn_Resolver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ResolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ResolverActionPerformed
        // TODO add your handling code here:

        try {
            if (iteraciones.validCheck(tbl_Matriz)) {
                int N = 2;
                int rows = 0, columns = 0;
                rows = tbl_Matriz.getRowCount();
                columns = tbl_Matriz.getColumnCount();

                Object object_A[][] = iteraciones.getTableData(tbl_Matriz);
                double m_A[][] = new double[rows][columns];

                for (int i = 0; i < tbl_Matriz.getRowCount(); i++) {
                    for (int j = 0; j < tbl_Matriz.getColumnCount(); j++) {
                        m_A[i][j] = Double.parseDouble((String) object_A[i][j]);
                    }
                }

                double adj[][] = new double[rows][columns];
                double inv[][] = new double[rows][columns];

                Inversa_Proceso proceso = new Inversa_Proceso();
                proceso.adjoint(m_A, adj, rows);

                if (proceso.inverse(m_A, inv, rows)) {
                    iteraciones.mostrar_Matriz(inv, rows, columns, tbl_Resultado1);
                    iteraciones.centrar(tbl_Resultado1);

                    jLabel7.setVisible(true);
                }

            } else {
                JOptionPane.showMessageDialog(null, "Debes llenar todos los campos");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Debe llenar todas las celdas");
        }
    }//GEN-LAST:event_btn_ResolverActionPerformed

    private void btn_AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AceptarActionPerformed
        // TODO add your handling code here:
        int rows = 0, columns = 0;
        try {
            rows = Integer.parseInt(txt_filas.getText());
            columns = Integer.parseInt(txt_Col.getText());

            if (!(rows == columns)) {
                JOptionPane.showMessageDialog(null, "La matriz debe ser cuadrada para calcualar su inversa");
            } else {
                Tabla_Iteraciones matrix_Iteraciones = new Tabla_Iteraciones();
                matrix_Iteraciones.generar(rows, columns, tbl_Matriz);
                matrix_Iteraciones.centrar(tbl_Matriz);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ingrese solo números");
        }
    }//GEN-LAST:event_btn_AceptarActionPerformed

    private void txt_filasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_filasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_filasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Aceptar;
    private javax.swing.JButton btn_Resolver;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tbl_Matriz;
    private javax.swing.JTable tbl_Resultado1;
    private javax.swing.JTextField txt_Col;
    private javax.swing.JTextField txt_filas;
    // End of variables declaration//GEN-END:variables
}
