package paneles;

import clases.Tabla_Iteraciones;
import clases.Inversa_Proceso;
import clases.Convert_To_Fraction;
import java.awt.Color;
import javax.swing.JOptionPane;

public class pnl_Ecuacion extends javax.swing.JPanel {
    
    Tabla_Iteraciones iteraciones = new Tabla_Iteraciones();

    public pnl_Ecuacion() {
        initComponents();

        //Colocar el rectangulo detras de la tabla de un color personalizado
        jScrollPane1.getViewport().setBackground(Color.white);
        jScrollPane3.getViewport().setBackground(Color.white);

        //Colocar el texto de la seleccion de un color personalizado
        tbl_Matriz.setSelectionForeground(Color.black);
        tbl_Valor_Independiente.setSelectionForeground(Color.black);
        
        iteraciones.centrar(tbl_Matriz);
        iteraciones.centrar(tbl_Valor_Independiente);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_Valor_Independiente = new javax.swing.JTable();
        btn_Resolver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Matriz = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_X_Uno = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_X_Dos = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_X_Tres = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(38, 86, 186));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Resolver ecuaciones con matriz adjunta");

        tbl_Valor_Independiente.setAutoCreateRowSorter(true);
        tbl_Valor_Independiente.setBackground(new java.awt.Color(204, 199, 228));
        tbl_Valor_Independiente.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        tbl_Valor_Independiente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        tbl_Valor_Independiente.setGridColor(new java.awt.Color(155, 154, 163));
        tbl_Valor_Independiente.setSelectionBackground(new java.awt.Color(204, 199, 228));
        tbl_Valor_Independiente.setShowGrid(true);
        tbl_Valor_Independiente.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tbl_Valor_Independiente);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setViewportView(  tbl_Valor_Independiente  );
        jScrollPane3.setColumnHeaderView( tbl_Valor_Independiente.getTableHeader());

        jScrollPane3.getColumnHeader().setVisible(false);
        jScrollPane3.revalidate();
        jScrollPane3.setBorder(null);

        btn_Resolver.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        btn_Resolver.setText("Resolver");
        btn_Resolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ResolverActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        tbl_Matriz.setAutoCreateRowSorter(true);
        tbl_Matriz.setBackground(new java.awt.Color(204, 199, 228));
        tbl_Matriz.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        tbl_Matriz.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        tbl_Matriz.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tbl_Matriz.setGridColor(new java.awt.Color(155, 154, 163));
        tbl_Matriz.setSelectionBackground(new java.awt.Color(204, 199, 228));
        tbl_Matriz.setShowGrid(true);
        jScrollPane1.setViewportView(tbl_Matriz);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setViewportView(  tbl_Matriz  );
        jScrollPane1.setColumnHeaderView( tbl_Matriz.getTableHeader());

        jScrollPane1.getColumnHeader().setVisible(false);
        jScrollPane1.revalidate();
        jScrollPane1.setBorder(null);

        jLabel6.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel6.setText("Ingresa los valores de la matriz");

        jLabel7.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel7.setText("Valores independientes");

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel2.setText("X1:");

        lbl_X_Uno.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel3.setText("X2:");

        lbl_X_Dos.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel4.setText("X3:");

        lbl_X_Tres.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel1.setText("Valores de incongnitas:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                        .addGap(81, 81, 81)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(btn_Resolver)
                        .addGap(182, 182, 182))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(66, 66, 66)
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_X_Tres, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lbl_X_Dos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lbl_X_Uno, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Resolver))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addComponent(lbl_X_Uno, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(lbl_X_Dos, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(lbl_X_Tres, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(87, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ResolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ResolverActionPerformed
        // TODO add your handling code here:
        int N = 3;

        try {
            if (iteraciones.validCheck(tbl_Matriz) && iteraciones.validCheck(tbl_Valor_Independiente)) {
                Object object_A[][] = iteraciones.getTableData(tbl_Matriz);
                double m_A[][] = new double[N][N];
                Object object_Independiente[][] = iteraciones.getTableData(tbl_Valor_Independiente);
                double m_Ind[][] = new double[3][1];

                for (int i = 0; i < tbl_Matriz.getRowCount(); i++) {
                    for (int j = 0; j < tbl_Matriz.getColumnCount(); j++) {
                        m_A[i][j] = Double.parseDouble((String) object_A[i][j]);
                    }
                }
                for (int i = 0; i < tbl_Valor_Independiente.getRowCount(); i++) {
                    for (int j = 0; j < tbl_Valor_Independiente.getColumnCount(); j++) {
                        m_Ind[i][j] = Double.parseDouble((String) object_Independiente[i][j]);
                    }
                }

                double adj[][] = new double[N][N];
                double inv[][] = new double[N][N];

                Inversa_Proceso proceso = new Inversa_Proceso();
                proceso.adjoint(m_A, adj, N);

                double result[][] = new double[3][1];
                
                if(proceso.inverse(m_A, inv, N)){
                    proceso.multiplicacion_Matriz(inv, m_Ind, result, 1, 3);
                    Convert_To_Fraction fraction = new Convert_To_Fraction();

                lbl_X_Uno.setText(String.valueOf(fraction.convertDecimalToFraction(result[0][0])));
                lbl_X_Dos.setText(String.valueOf(fraction.convertDecimalToFraction(result[1][0])));
                lbl_X_Tres.setText(String.valueOf(fraction.convertDecimalToFraction(result[2][0])));
                }else{
                    JOptionPane.showMessageDialog(null, "No se puede calcular la inversa");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Debes llenar todos los campos");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Debe llenar correctamente todas las celdas");
        }


    }//GEN-LAST:event_btn_ResolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Resolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_X_Dos;
    private javax.swing.JLabel lbl_X_Tres;
    private javax.swing.JLabel lbl_X_Uno;
    private javax.swing.JTable tbl_Matriz;
    private javax.swing.JTable tbl_Valor_Independiente;
    // End of variables declaration//GEN-END:variables
}
