/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import javax.swing.JOptionPane;
import clases.Tabla_Iteraciones;
import clases.Convert_To_Fraction;
import clases.Ecuaciones;
import java.awt.Color;

public class pnl_GaussJordan extends javax.swing.JPanel {

    /**
     * Creates new form pnlHome
     */
    public pnl_GaussJordan() {
        initComponents();

        jScrollPane1.getViewport().setBackground(Color.white);
        jScrollPane2.getViewport().setBackground(Color.white);

        tbl_Matriz.setSelectionForeground(Color.black);
        tbl_Resultado.setSelectionForeground(Color.black);
        tbl_Resultado.setEnabled(false);

        iteraciones.centrar(tbl_Matriz);

        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel7.setVisible(false);
    }
    Tabla_Iteraciones iteraciones = new Tabla_Iteraciones();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_Resultado = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbl_X_Dos = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_X_Tres = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Matriz = new javax.swing.JTable();
        lbl_X_Uno = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(38, 86, 186));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Eliminación por Gauss-Jordan");

        jButton1.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jButton1.setText("Resolver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tbl_Resultado.setAutoCreateRowSorter(true);
        tbl_Resultado.setBackground(new java.awt.Color(204, 199, 228));
        tbl_Resultado.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        tbl_Resultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbl_Resultado.setGridColor(new java.awt.Color(155, 154, 163));
        tbl_Resultado.setSelectionBackground(new java.awt.Color(204, 199, 228));
        tbl_Resultado.setShowGrid(true);
        tbl_Resultado.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tbl_Resultado);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setViewportView(  tbl_Resultado  );
        jScrollPane2.setColumnHeaderView( tbl_Resultado.getTableHeader());

        jScrollPane2.getColumnHeader().setVisible(false);
        jScrollPane2.revalidate();
        jScrollPane2.setBorder(null);

        jLabel7.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel7.setText("Matriz final:");

        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel3.setText("X2:");

        jLabel6.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel6.setText("Ingresa los valores de la matriz");

        lbl_X_Dos.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel4.setText("X3:");

        lbl_X_Tres.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel1.setText("Valores de incongnitas:");

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel2.setText("X1:");

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        tbl_Matriz.setAutoCreateRowSorter(true);
        tbl_Matriz.setBackground(new java.awt.Color(204, 199, 228));
        tbl_Matriz.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        tbl_Matriz.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_Matriz.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tbl_Matriz.setGridColor(new java.awt.Color(155, 154, 163));
        tbl_Matriz.setSelectionBackground(new java.awt.Color(204, 199, 228));
        tbl_Matriz.setShowGrid(true);
        jScrollPane1.setViewportView(tbl_Matriz);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setViewportView(  tbl_Matriz  );
        jScrollPane1.setColumnHeaderView( tbl_Matriz.getTableHeader());

        jScrollPane1.getColumnHeader().setVisible(false);
        jScrollPane1.revalidate();
        jScrollPane1.setBorder(null);

        lbl_X_Uno.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_X_Tres, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lbl_X_Dos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lbl_X_Uno, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(108, 108, 108)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(171, 171, 171))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2))
                                    .addComponent(lbl_X_Uno, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(lbl_X_Dos, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(lbl_X_Tres, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(89, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        int fila = 3, columna_A = 4, i = 0, j = 0;

        try {
            if (iteraciones.validCheck(tbl_Matriz)) {
                Ecuaciones ecuaciones = new Ecuaciones();

                Object object_A[][] = iteraciones.getTableData(tbl_Matriz);

                double m_A[][] = new double[fila][columna_A];

                for (i = 0; i < tbl_Matriz.getRowCount(); i++) {
                    for (j = 0; j < tbl_Matriz.getColumnCount(); j++) {
                        m_A[i][j] = Double.parseDouble((String) object_A[i][j]);
                    }
                }

                // Orden de  Matriz(n)
                int n = 3, flag = 0;
                // Realización de la transformación de matriz
                flag = ecuaciones.PerformOperation(m_A, n);

                if (flag == 1) {
                    flag = ecuaciones.CheckConsistency(m_A, n, flag);
                }
                if (flag == 2) {
                    JOptionPane.showMessageDialog(null, "El sistema tiene soluciones infinitas");
                }
                if (flag == 3) {
                    JOptionPane.showMessageDialog(null, "El sistema no tiene soluciones");
                } // Imprimir la solución dividiendo constantes por
                 // sus respectivos elementos diagonales
                else {
                    double suma;
                    int ORDEN = 3;
                    double x[] = new double[ORDEN];
                    for (i = ORDEN - 1; i >= 0; i--) { 
                        suma = 0;
                        for (j = i + 1; j <= ORDEN - 1; j++) { 
                            suma = suma + m_A[i][j] * x[j]; 
                        }
                        //Obtener los valores de las variables
                        x[i] = (m_A[i][ORDEN] - suma) / m_A[i][i];
                    }
                    Convert_To_Fraction fraction = new Convert_To_Fraction();
                    jLabel1.setVisible(true);
                    jLabel2.setVisible(true);
                    jLabel3.setVisible(true);
                    jLabel4.setVisible(true);
                    jLabel7.setVisible(true);

                    lbl_X_Uno.setText(String.valueOf(fraction.convertDecimalToFraction(x[0])));
                    lbl_X_Dos.setText(String.valueOf(fraction.convertDecimalToFraction(x[1])));
                    lbl_X_Tres.setText(String.valueOf(fraction.convertDecimalToFraction(x[2])));

                    iteraciones.mostrar_Matriz(m_A, fila, columna_A, tbl_Resultado);
                    iteraciones.centrar(tbl_Resultado);

                }
            } else {
                JOptionPane.showMessageDialog(null, "Debes llenar todos los campos");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Debe llenar todas las celdas");
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_X_Dos;
    private javax.swing.JLabel lbl_X_Tres;
    private javax.swing.JLabel lbl_X_Uno;
    private javax.swing.JTable tbl_Matriz;
    private javax.swing.JTable tbl_Resultado;
    // End of variables declaration//GEN-END:variables
}
