package paneles;

import javax.swing.JOptionPane;
import clases.Tabla_Iteraciones;
import java.awt.Color;

public class Suma_Matrices extends javax.swing.JPanel {

    Tabla_Iteraciones iteraciones = new Tabla_Iteraciones();

    public Suma_Matrices() {
        initComponents();

        //Colocar el rectangulo detras de la tabla de un color personalizado
        jScrollPane1.getViewport().setBackground(Color.white);
        jScrollPane2.getViewport().setBackground(Color.white);
        jScrollPane3.getViewport().setBackground(Color.white);

        //Colocar el texto de la seleccion de un color personalizado
        tbl_Matriz.setSelectionForeground(Color.black);
        tbl_MatrizB.setSelectionForeground(Color.black);

        tbl_MatrizC.setEnabled(false);

        btn_Sumar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        btn_Aceptar = new javax.swing.JButton();
        txt_Col = new javax.swing.JTextField();
        btn_Sumar = new javax.swing.JButton();
        txt_ColB = new javax.swing.JTextField();
        txt_filasB = new javax.swing.JTextField();
        txt_filas = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Matriz = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_MatrizB = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_MatrizC = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(38, 86, 186));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Suma de matrices");

        btn_Aceptar.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        btn_Aceptar.setText("Crear matriz");
        btn_Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AceptarActionPerformed(evt);
            }
        });

        txt_Col.setBackground(new java.awt.Color(239, 238, 244));
        txt_Col.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        txt_Col.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Col.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btn_Sumar.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        btn_Sumar.setText("Sumar");
        btn_Sumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SumarActionPerformed(evt);
            }
        });

        txt_ColB.setBackground(new java.awt.Color(239, 238, 244));
        txt_ColB.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        txt_ColB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_ColB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        txt_filasB.setBackground(new java.awt.Color(239, 238, 244));
        txt_filasB.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        txt_filasB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_filasB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        txt_filas.setBackground(new java.awt.Color(239, 238, 244));
        txt_filas.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        txt_filas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_filas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txt_filas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_filasActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel2.setText("Columnas primer matriz:");

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        tbl_Matriz.setAutoCreateRowSorter(true);
        tbl_Matriz.setBackground(new java.awt.Color(204, 199, 228));
        tbl_Matriz.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        tbl_Matriz.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbl_Matriz.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tbl_Matriz.setGridColor(new java.awt.Color(155, 154, 163));
        tbl_Matriz.setSelectionBackground(new java.awt.Color(204, 199, 228));
        tbl_Matriz.setShowGrid(true);
        jScrollPane1.setViewportView(tbl_Matriz);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setViewportView(  tbl_Matriz  );
        jScrollPane1.setColumnHeaderView( tbl_Matriz.getTableHeader());

        jScrollPane1.getColumnHeader().setVisible(false);
        jScrollPane1.revalidate();
        jScrollPane1.setBorder(null);

        tbl_MatrizB.setAutoCreateRowSorter(true);
        tbl_MatrizB.setBackground(new java.awt.Color(204, 199, 228));
        tbl_MatrizB.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        tbl_MatrizB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbl_MatrizB.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tbl_MatrizB.setGridColor(new java.awt.Color(155, 154, 163));
        tbl_MatrizB.setSelectionBackground(new java.awt.Color(204, 199, 228));
        tbl_MatrizB.setShowGrid(true);
        tbl_MatrizB.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tbl_MatrizB);
        //jScrollPane2.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_NEVER);
        //jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setViewportView(  tbl_MatrizB  );
        jScrollPane2.setColumnHeaderView( tbl_MatrizB.getTableHeader());

        jScrollPane2.getColumnHeader().setVisible(false);
        jScrollPane2.revalidate();
        jScrollPane2.setBorder(null);

        tbl_MatrizC.setAutoCreateRowSorter(true);
        tbl_MatrizC.setBackground(new java.awt.Color(204, 199, 228));
        tbl_MatrizC.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        tbl_MatrizC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbl_MatrizC.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tbl_MatrizC.setGridColor(new java.awt.Color(155, 154, 163));
        tbl_MatrizC.setSelectionBackground(new java.awt.Color(204, 199, 228));
        tbl_MatrizC.setShowGrid(true);
        tbl_MatrizC.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tbl_MatrizC);
        //jScrollPane2.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_NEVER);
        //jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setViewportView(  tbl_MatrizC  );
        jScrollPane3.setColumnHeaderView( tbl_MatrizC.getTableHeader());

        jScrollPane3.getColumnHeader().setVisible(false);
        jScrollPane3.revalidate();
        jScrollPane3.setBorder(null);

        jLabel6.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel6.setText("Filas primer matriz:");

        jLabel7.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel7.setText("Filas segunda matriz:");

        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel3.setText("Columnas segunda matriz:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Col, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(txt_filas, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_filasB, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_Aceptar)
                                .addGap(18, 18, 18)
                                .addComponent(btn_Sumar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_ColB, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_filasB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addGap(39, 39, 39))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_filas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_Col, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_ColB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Sumar)
                            .addComponent(btn_Aceptar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AceptarActionPerformed
        // TODO add your handling code here:
        int rows = 0, columns = 0, rows_B = 0, columns_B = 0;
        iteraciones.borrar_Tabla(tbl_Matriz);
        iteraciones.borrar_Tabla(tbl_MatrizB);

        JOptionPane.showMessageDialog(null, "Ingresa los valores haciendo click en cada casilla");

        try {
            rows = Integer.parseInt(txt_filas.getText());
            columns = Integer.parseInt(txt_Col.getText());
            rows_B = Integer.parseInt(txt_filasB.getText());
            columns_B = Integer.parseInt(txt_ColB.getText());

            if ((rows != rows_B) || (columns != columns_B)) {
                JOptionPane.showMessageDialog(null, "La suma no esta definida, las "
                        + "matrices deben ser del mismo tamaño para poderse sumar");
            } else {
                iteraciones.generar(rows, columns, tbl_Matriz);
                iteraciones.generar(rows_B, columns_B, tbl_MatrizB);
                iteraciones.centrar(tbl_Matriz);
                iteraciones.centrar(tbl_MatrizB);
                btn_Sumar.setEnabled(true);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Favor de llenar correctamente todos los campos");
        }
    }//GEN-LAST:event_btn_AceptarActionPerformed

    private void btn_SumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SumarActionPerformed
        // TODO add your handling code here:
        int fila = 0, columna = 0, i = 0, j = 0;

        try {

            if (iteraciones.validCheck(tbl_Matriz) && iteraciones.validCheck(tbl_MatrizB)) {
                fila = Integer.parseInt(txt_filas.getText());
                columna = Integer.parseInt(txt_Col.getText());

                Object object_A[][] = iteraciones.getTableData(tbl_Matriz);
                Object object_B[][] = iteraciones.getTableData(tbl_MatrizB);

                double m_A[][] = new double[fila][columna];
                double m_B[][] = new double[fila][columna];
                double matrix_C[][] = new double[fila][columna];

                for (i = 0; i < tbl_Matriz.getRowCount(); i++) {
                    for (j = 0; j < tbl_Matriz.getColumnCount(); j++) {
                        m_A[i][j] = Double.parseDouble((String) object_A[i][j]);
                        m_B[i][j] = Double.parseDouble((String) object_B[i][j]);
                    }
                }
                for (i = 0; i < tbl_Matriz.getRowCount(); i++) {
                    for (j = 0; j < tbl_Matriz.getColumnCount(); j++) {
                        matrix_C[i][j] = m_A[i][j] + m_B[i][j];
                    }
                }

                iteraciones.mostrar_Matriz(matrix_C, fila, columna, tbl_MatrizC);
                iteraciones.centrar(tbl_MatrizC);

            } else {
                JOptionPane.showMessageDialog(null, "Debes llenar todos los campos");
            }
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Debe llenar todas las celdas");

        }
    }//GEN-LAST:event_btn_SumarActionPerformed

    private void txt_filasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_filasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_filasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Aceptar;
    private javax.swing.JButton btn_Sumar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tbl_Matriz;
    private javax.swing.JTable tbl_MatrizB;
    private javax.swing.JTable tbl_MatrizC;
    private javax.swing.JTextField txt_Col;
    private javax.swing.JTextField txt_ColB;
    private javax.swing.JTextField txt_filas;
    private javax.swing.JTextField txt_filasB;
    // End of variables declaration//GEN-END:variables
}
